export const apiFailJson = `{
    "correlationId": "101e6844",
    "title": "Unexpected Problem",
    "type": "https://api.weather.gov/problems/UnexpectedProblem",
    "status": 500,
    "detail": "An unexpected problem has occurred.",
    "instance": "https://api.weather.gov/requests/101e6844"
  }`;

export const apiSuccessJson = {
  "@context": [
    "https://geojson.org/geojson-ld/geojson-context.jsonld",
    {
      "@version": "1.1",
      wx: "https://api.weather.gov/ontology#",
      geo: "http://www.opengis.net/ont/geosparql#",
      unit: "http://codes.wmo.int/common/unit/",
      "@vocab": "https://api.weather.gov/ontology#",
    },
  ],
  type: "Feature",
  geometry: {
    type: "Polygon",
    coordinates: [
      [
        [-119.7772172, 34.4107065],
        [-119.7722581, 34.388564900000006],
        [-119.7454046, 34.392657400000004],
        [-119.7503586, 34.41479950000001],
        [-119.7772172, 34.4107065],
      ],
    ],
  },
  properties: {
    updated: "2022-11-20T17:14:50+00:00",
    units: "us",
    forecastGenerator: "BaselineForecastGenerator",
    generatedAt: "2022-11-20T21:52:21+00:00",
    updateTime: "2022-11-20T17:14:50+00:00",
    validTimes: "2022-11-20T11:00:00+00:00/P7DT14H",
    elevation: { unitCode: "wmoUnit:m", value: 0 },
    periods: [
      {
        number: 1,
        name: "S Day 1",
        startTime: "2022-11-20T13:00:00-08:00",
        endTime: "2022-11-20T18:00:00-08:00",
        isDaytime: true,
        temperature: 68,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 to 10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=medium",
        shortForecast: "Sunny",
        detailedForecast: "Sunny, with a high near 68. West wind 5 to 10 mph.",
      },
      {
        number: 2,
        name: "S Night 1",
        startTime: "2022-11-20T18:00:00-08:00",
        endTime: "2022-11-21T06:00:00-08:00",
        isDaytime: false,
        temperature: 50,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 to 5 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/few?size=medium",
        shortForecast: "Mostly Clear",
        detailedForecast:
          "Mostly clear, with a low around 50. Northeast wind 0 to 5 mph.",
      },
      {
        number: 3,
        name: "S Day 2",
        startTime: "2022-11-21T06:00:00-08:00",
        endTime: "2022-11-21T18:00:00-08:00",
        isDaytime: true,
        temperature: 63,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 to 10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/sct?size=medium",
        shortForecast: "Mostly Sunny",
        detailedForecast:
          "Mostly sunny, with a high near 63. West wind 0 to 10 mph.",
      },
      {
        number: 4,
        name: "S Night 2",
        startTime: "2022-11-21T18:00:00-08:00",
        endTime: "2022-11-22T06:00:00-08:00",
        isDaytime: false,
        temperature: 49,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 to 10 mph",
        windDirection: "NNW",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=medium",
        shortForecast: "Mostly Cloudy",
        detailedForecast:
          "Mostly cloudy, with a low around 49. North northwest wind 5 to 10 mph.",
      },
      {
        number: 5,
        name: "S Day 3",
        startTime: "2022-11-22T06:00:00-08:00",
        endTime: "2022-11-22T18:00:00-08:00",
        isDaytime: true,
        temperature: 64,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/sct?size=medium",
        shortForecast: "Mostly Sunny",
        detailedForecast:
          "Mostly sunny, with a high near 64. Northwest wind around 5 mph.",
      },
      {
        number: 6,
        name: "S Night 3",
        startTime: "2022-11-22T18:00:00-08:00",
        endTime: "2022-11-23T06:00:00-08:00",
        isDaytime: false,
        temperature: 49,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NNW",
        icon: "https://api.weather.gov/icons/land/night/few?size=medium",
        shortForecast: "Mostly Clear",
        detailedForecast: "Mostly clear, with a low around 49.",
      },
      {
        number: 7,
        name: "S Day 4",
        startTime: "2022-11-23T06:00:00-08:00",
        endTime: "2022-11-23T18:00:00-08:00",
        isDaytime: true,
        temperature: 63,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=medium",
        shortForecast: "Sunny",
        detailedForecast: "Sunny, with a high near 63.",
      },
      {
        number: 8,
        name: "S Night 4",
        startTime: "2022-11-23T18:00:00-08:00",
        endTime: "2022-11-24T06:00:00-08:00",
        isDaytime: false,
        temperature: 51,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 to 10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/few?size=medium",
        shortForecast: "Mostly Clear",
        detailedForecast: "Mostly clear, with a low around 51.",
      },
      {
        number: 9,
        name: "S Day 5",
        startTime: "2022-11-24T06:00:00-08:00",
        endTime: "2022-11-24T18:00:00-08:00",
        isDaytime: true,
        temperature: 69,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NNW",
        icon: "https://api.weather.gov/icons/land/day/few?size=medium",
        shortForecast: "Sunny",
        detailedForecast: "Sunny, with a high near 69.",
      },
      {
        number: 10,
        name: "S Night 5",
        startTime: "2022-11-24T18:00:00-08:00",
        endTime: "2022-11-25T06:00:00-08:00",
        isDaytime: false,
        temperature: 53,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 to 10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/few?size=medium",
        shortForecast: "Mostly Clear",
        detailedForecast: "Mostly clear, with a low around 53.",
      },
      {
        number: 11,
        name: "S Day 6",
        startTime: "2022-11-25T06:00:00-08:00",
        endTime: "2022-11-25T18:00:00-08:00",
        isDaytime: true,
        temperature: 67,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 to 10 mph",
        windDirection: "WNW",
        icon: "https://api.weather.gov/icons/land/day/few?size=medium",
        shortForecast: "Sunny",
        detailedForecast: "Sunny, with a high near 67.",
      },
      {
        number: 12,
        name: "S Night 6",
        startTime: "2022-11-25T18:00:00-08:00",
        endTime: "2022-11-26T06:00:00-08:00",
        isDaytime: false,
        temperature: 52,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "NNW",
        icon: "https://api.weather.gov/icons/land/night/few?size=medium",
        shortForecast: "Mostly Clear",
        detailedForecast: "Mostly clear, with a low around 52.",
      },
      {
        number: 13,
        name: "S Day 7",
        startTime: "2022-11-26T06:00:00-08:00",
        endTime: "2022-11-26T18:00:00-08:00",
        isDaytime: true,
        temperature: 65,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 to 10 mph",
        windDirection: "WNW",
        icon: "https://api.weather.gov/icons/land/day/few?size=medium",
        shortForecast: "Sunny",
        detailedForecast: "Sunny, with a high near 65.",
      },
      {
        number: 14,
        name: "S Night 7",
        startTime: "2022-11-26T18:00:00-08:00",
        endTime: "2022-11-27T06:00:00-08:00",
        isDaytime: false,
        temperature: 50,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 to 15 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/night/sct?size=medium",
        shortForecast: "Partly Cloudy",
        detailedForecast: "Partly cloudy, with a low around 50.",
      },
    ],
  },
};
