name: "deploy to github pages"
# borrowed from   https://github.com/actions/upload-pages-artifact/blob/main/action.yml
inputs:
  path:
    description: "Path of the directory containing the static assets."
    required: true
    default: "build/"
  retention-days:
    description: "Duration after which artifact will expire in days."
    required: false
    default: "1"
on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: yarn --frozen-lockfile
      - run: yarn build
      - name: Archive artifact
        shell: sh
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
        env:
          INPUT_PATH: ${{ inputs.path }}
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: ${{ inputs.retention-days }}
